image: node

build-job:
  tags:
    - docker
  stage: build
  script:
    - npm install -D eslint eslint-config-prettier eslint-config-universe
    - npx eslint --fix --ext .js,.jsx .


tests:
  tags:
    - docker
  stage: test
  script:
    - echo "Jest tests here"
