image: node

build-job:
  tags:
    - docker
  stage: build
  script:
    - npm install eslint-plugin-react@latest --save-dev
    - npm install @react-native-community/eslint-config --save-dev
    - npx eslint --fix --ext .js,.jsx .


tests:
  tags:
    - docker
  stage: test
  script:
    - echo "Jest tests here"
