env:
  es2021: true
  jest: true  # Keep this if you're using Jest for testing in your React Native project
extends:
  - '@react-native-community'  # Use the React Native community's recommended ESLint settings
  - prettier
parser: babel-eslint  # Use babel-eslint parser
parserOptions:
  ecmaVersion: latest
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - react-native  # Add the react-native plugin
  - prettier
  - import
settings:
  react:
    version: 'detect'
rules:
  react/react-in-jsx-scope: 'off'
  react/jsx-uses-react: 'off'   
  react/jsx-uses-vars: 'error'
  no-unused-vars: 'error'
  react/prop-types: 'off'
  react-native/no-unused-styles: 'warn'  # Warn about unused styles
  react-native/split-platform-components: 'warn'  # Enforce using platform-specific components
  react-native/no-inline-styles: 'off'  # Decide based on your preference
  react-native/no-raw-text: 'off'  # Prevent usage of raw text outside of Text components; adjust as necessary
  prettier/prettier: 'error'  # Warn about code formatting issues
  no-alert: 'off'
  import/order: 'error'
babelOptions:
  configFile: './babel.config.js'  # Specify the location of the Babel config file
